export interface FacultyProfile {
  employeeId: string;
  name: string;
  email: string;
  password?: string;
  department: string; // e.g. "CSE", "AIML", "AIDS", "CYBERSECURITY", "IT", "ECE", "EEE", "MECH", "CIVIL"
  departmentFullName: string;
  designation: 'Professor' | 'Associate Professor' | 'Assistant Professor' | 'Lecturer';
  category: 'Teaching' | 'Non-Teaching';
  baseSalary: number;
  gender: string;
  phone: string;
  experience: number;
  joiningDate: string;
  qualification: string;
  specialization: string;
  researchInterests: string;
  officeLocation: string;
  status: 'Active' | 'On Leave' | 'Inactive';
  avatar: string;
  workingDays: number;
  presentDays: number;
  absentDays: number;
  leaveDays: number;
  assignedSubjects?: string[];
  assignedClasses?: string[];
}

export interface DepartmentInfo {
  code: string;
  name: string;
}

export const DEPARTMENTS_LIST: DepartmentInfo[] = [
  { code: 'CSE', name: 'Computer Science & Engineering (CSE)' },
  { code: 'AIML', name: 'Artificial Intelligence & Machine Learning (AIML)' },
  { code: 'AIDS', name: 'Artificial Intelligence & Data Science (AIDS)' },
  { code: 'CYBERSECURITY', name: 'Cyber Security' },
  { code: 'ECE', name: 'Electronics & Communication Engineering (ECE)' },
  { code: 'EEE', name: 'Electrical & Electronics Engineering (EEE)' },
  { code: 'IT', name: 'Information Technology (IT)' },
  { code: 'MECH', name: 'Mechanical Engineering' },
  { code: 'CIVIL', name: 'Civil Engineering' },
];

export const DEFAULT_FACULTY_PASSWORD = 'password123';

export const ALL_FACULTY_MEMBERS: FacultyProfile[] = [
  // ── Computer Science & Engineering (CSE) ──
  {
    employeeId: 'FAC2020001',
    name: 'Dr. John Smith',
    email: 'faculty@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'CSE',
    departmentFullName: 'Computer Science & Engineering',
    designation: 'Associate Professor',
    category: 'Teaching',
    baseSalary: 80000,
    gender: 'Male',
    phone: '9876543212',
    experience: 12,
    joiningDate: '2018-06-15',
    qualification: 'Ph.D. Computer Science',
    specialization: 'Database Systems & Cloud Computing',
    researchInterests: 'Distributed Databases, Query Optimization',
    officeLocation: 'Block A - Room 302',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 29,
    absentDays: 1,
    leaveDays: 0,
    assignedSubjects: ['Database Management Systems', 'Cloud Computing Architecture'],
    assignedClasses: ['CSE-3A', 'CSE-4B'],
  },
  {
    employeeId: 'FACCSE1',
    name: 'Kambhampati Harish',
    email: 'faculty.cse.1@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'CSE',
    departmentFullName: 'Computer Science & Engineering',
    designation: 'Professor',
    category: 'Teaching',
    baseSalary: 95000,
    gender: 'Male',
    phone: '9848067831',
    experience: 8,
    joiningDate: '2016-08-10',
    qualification: 'Ph.D. Computer Science & Engineering',
    specialization: 'Advanced Data Structures & Graph Algorithms',
    researchInterests: 'Parallel Computing, High Performance Systems',
    officeLocation: 'Block A - Room 305 (HOD Lab)',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 30,
    absentDays: 0,
    leaveDays: 0,
    assignedSubjects: ['Data Structures & Algorithms', 'Design & Analysis of Algorithms'],
    assignedClasses: ['CSE-2A', 'CSE-3B'],
  },
  {
    employeeId: 'FACCSE2',
    name: 'Thota Sujatha',
    email: 'faculty.cse.2@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'CSE',
    departmentFullName: 'Computer Science & Engineering',
    designation: 'Associate Professor',
    category: 'Teaching',
    baseSalary: 80000,
    gender: 'Female',
    phone: '9848067832',
    experience: 11,
    joiningDate: '2019-03-20',
    qualification: 'M.Tech CSE, Ph.D.',
    specialization: 'Software Engineering & Web Technologies',
    researchInterests: 'DevOps Automations, Modern UI Architecture',
    officeLocation: 'Block A - Room 308',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 28,
    absentDays: 2,
    leaveDays: 1,
    assignedSubjects: ['Software Engineering', 'Full Stack Web Development'],
    assignedClasses: ['CSE-3A', 'CSE-3C'],
  },
  {
    employeeId: 'FACCSE3',
    name: 'Duggirala Anand',
    email: 'faculty.cse.3@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'CSE',
    departmentFullName: 'Computer Science & Engineering',
    designation: 'Assistant Professor',
    category: 'Teaching',
    baseSalary: 65000,
    gender: 'Male',
    phone: '9848067833',
    experience: 6,
    joiningDate: '2021-07-01',
    qualification: 'M.Tech Computer Science',
    specialization: 'Operating Systems & System Architecture',
    researchInterests: 'Linux Kernel Modules, Embedded Systems OS',
    officeLocation: 'Block A - Room 310',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 27,
    absentDays: 3,
    leaveDays: 1,
    assignedSubjects: ['Operating Systems', 'Computer Organization'],
    assignedClasses: ['CSE-2B', 'CSE-2C'],
  },

  // ── Artificial Intelligence & Machine Learning (AIML) ──
  {
    employeeId: 'FACAIML1',
    name: 'Kondapalli Bhargav',
    email: 'faculty.aiml.1@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'AIML',
    departmentFullName: 'Artificial Intelligence & Machine Learning',
    designation: 'Professor',
    category: 'Teaching',
    baseSalary: 95000,
    gender: 'Male',
    phone: '9848065731',
    experience: 16,
    joiningDate: '2016-06-20',
    qualification: 'Ph.D. Machine Learning & Neural Networks',
    specialization: 'Deep Learning, Computer Vision & NLP',
    researchInterests: 'Generative AI Models, Transformer Architectures',
    officeLocation: 'AIML Block - Room 101',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 29,
    absentDays: 1,
    leaveDays: 0,
    assignedSubjects: ['Deep Learning Systems', 'Natural Language Processing'],
    assignedClasses: ['AIML-3A', 'AIML-4A'],
  },
  {
    employeeId: 'FACAIML2',
    name: 'Thota Sunitha',
    email: 'faculty.aiml.2@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'AIML',
    departmentFullName: 'Artificial Intelligence & Machine Learning',
    designation: 'Associate Professor',
    category: 'Teaching',
    baseSalary: 80000,
    gender: 'Female',
    phone: '9848065732',
    experience: 11,
    joiningDate: '2019-01-15',
    qualification: 'Ph.D. AI & Data Analytics',
    specialization: 'Reinforcement Learning & Statistical Models',
    researchInterests: 'Autonomous Robotics, Predictive AI Models',
    officeLocation: 'AIML Block - Room 104',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 28,
    absentDays: 2,
    leaveDays: 1,
    assignedSubjects: ['Machine Learning Principles', 'Pattern Recognition'],
    assignedClasses: ['AIML-2A', 'AIML-3B'],
  },
  {
    employeeId: 'FACAIML3',
    name: 'Alapati Vivek',
    email: 'faculty.aiml.3@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'AIML',
    departmentFullName: 'Artificial Intelligence & Machine Learning',
    designation: 'Assistant Professor',
    category: 'Teaching',
    baseSalary: 65000,
    gender: 'Male',
    phone: '9848065733',
    experience: 7,
    joiningDate: '2022-04-10',
    qualification: 'M.Tech Artificial Intelligence',
    specialization: 'Python AI Frameworks & TensorFlow',
    researchInterests: 'Edge AI Inference, Embedded Neural Networks',
    officeLocation: 'AIML Block - Room 107',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 30,
    absentDays: 0,
    leaveDays: 0,
    assignedSubjects: ['Python for Artificial Intelligence', 'Neural Network Labs'],
    assignedClasses: ['AIML-2B', 'AIML-2C'],
  },

  // ── Artificial Intelligence & Data Science (AIDS) ──
  {
    employeeId: 'FACAIDS1',
    name: 'Cherukuri Hari',
    email: 'faculty.aids.1@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'AIDS',
    departmentFullName: 'Artificial Intelligence & Data Science',
    designation: 'Professor',
    category: 'Teaching',
    baseSalary: 95000,
    gender: 'Male',
    phone: '9848065881',
    experience: 14,
    joiningDate: '2017-06-01',
    qualification: 'Ph.D. Data Science & Big Data Systems',
    specialization: 'Big Data Pipelines & Distributed Processing',
    researchInterests: 'Scalable ETL Engines, Streaming Analytics',
    officeLocation: 'AIDS Block - Room 201',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 29,
    absentDays: 1,
    leaveDays: 0,
    assignedSubjects: ['Big Data Analytics', 'Data Warehousing & Mining'],
    assignedClasses: ['AIDS-3A', 'AIDS-4A'],
  },
  {
    employeeId: 'FACAIDS2',
    name: 'Ravipati Sravani',
    email: 'faculty.aids.2@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'AIDS',
    departmentFullName: 'Artificial Intelligence & Data Science',
    designation: 'Associate Professor',
    category: 'Teaching',
    baseSalary: 80000,
    gender: 'Female',
    phone: '9848065882',
    experience: 10,
    joiningDate: '2020-02-18',
    qualification: 'Ph.D. Statistics & Machine Learning',
    specialization: 'Applied Statistics & Exploratory Data Analysis',
    researchInterests: 'Biomedical Data Analytics, Predictive Statistics',
    officeLocation: 'AIDS Block - Room 204',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 28,
    absentDays: 2,
    leaveDays: 0,
    assignedSubjects: ['Applied Statistics for Data Science', 'R Programming'],
    assignedClasses: ['AIDS-2A', 'AIDS-3B'],
  },
  {
    employeeId: 'FACAIDS3',
    name: 'Bandla Satish',
    email: 'faculty.aids.3@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'AIDS',
    departmentFullName: 'Artificial Intelligence & Data Science',
    designation: 'Assistant Professor',
    category: 'Teaching',
    baseSalary: 65000,
    gender: 'Male',
    phone: '9848065883',
    experience: 7,
    joiningDate: '2022-01-10',
    qualification: 'M.Tech Data Science',
    specialization: 'Data Visualization & Dashboard Engineering',
    researchInterests: 'Interactive Business Intelligence, Tableau & PowerBI',
    officeLocation: 'AIDS Block - Room 207',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 30,
    absentDays: 0,
    leaveDays: 0,
    assignedSubjects: ['Data Visualization Systems', 'SQL & NoSQL Databases'],
    assignedClasses: ['AIDS-2B', 'AIDS-2C'],
  },

  // ── Cyber Security ──
  {
    employeeId: 'FACCYBERSECURITY1',
    name: 'Ravipati Prathyush',
    email: 'faculty.cybersecurity.1@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'CYBERSECURITY',
    departmentFullName: 'Cyber Security',
    designation: 'Professor',
    category: 'Teaching',
    baseSalary: 95000,
    gender: 'Male',
    phone: '9848067891',
    experience: 15,
    joiningDate: '2016-05-15',
    qualification: 'Ph.D. Network Security & Cryptography',
    specialization: 'Ethical Hacking, Penetration Testing & Cryptanalysis',
    researchInterests: 'Zero Trust Network Architecture, Blockchain Security',
    officeLocation: 'Cyber Block - Room 401',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 30,
    absentDays: 0,
    leaveDays: 0,
    assignedSubjects: ['Network Security & Cryptography', 'Ethical Hacking & Defence'],
    assignedClasses: ['CYBER-3A', 'CYBER-4A'],
  },
  {
    employeeId: 'FACCYBERSECURITY2',
    name: 'Vemuri Ramya',
    email: 'faculty.cybersecurity.2@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'CYBERSECURITY',
    departmentFullName: 'Cyber Security',
    designation: 'Associate Professor',
    category: 'Teaching',
    baseSalary: 80000,
    gender: 'Female',
    phone: '9848067892',
    experience: 11,
    joiningDate: '2019-09-01',
    qualification: 'Ph.D. Cyber Forensics & Threat Intel',
    specialization: 'Malware Analysis & Digital Forensics',
    researchInterests: 'Threat Intelligence, Memory Forensics & SIEM',
    officeLocation: 'Cyber Block - Room 405',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 28,
    absentDays: 2,
    leaveDays: 1,
    assignedSubjects: ['Digital Forensics & Investigation', 'Cyber Law & Incident Response'],
    assignedClasses: ['CYBER-2A', 'CYBER-3B'],
  },
  {
    employeeId: 'FACCYBERSECURITY3',
    name: 'Kothapalli Chandra',
    email: 'faculty.cybersecurity.3@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'CYBERSECURITY',
    departmentFullName: 'Cyber Security',
    designation: 'Assistant Professor',
    category: 'Teaching',
    baseSalary: 65000,
    gender: 'Male',
    phone: '9848067893',
    experience: 6,
    joiningDate: '2021-11-15',
    qualification: 'M.Tech Information Security',
    specialization: 'Cloud Security & Application Security',
    researchInterests: 'Container Security, Web Security Scanners',
    officeLocation: 'Cyber Block - Room 408',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 29,
    absentDays: 1,
    leaveDays: 0,
    assignedSubjects: ['Cloud Security Architecture', 'Web Application Security'],
    assignedClasses: ['CYBER-2B', 'CYBER-2C'],
  },

  // ── Electronics & Communication Engineering (ECE) ──
  {
    employeeId: 'FACECE1',
    name: 'Nallamothu Prasad',
    email: 'faculty.ece.1@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'ECE',
    departmentFullName: 'Electronics & Communication Engineering',
    designation: 'Professor',
    category: 'Teaching',
    baseSalary: 95000,
    gender: 'Male',
    phone: '9848069671',
    experience: 15,
    joiningDate: '2015-06-10',
    qualification: 'Ph.D. VLSI Design & Embedded Systems',
    specialization: 'Digital Signal Processing & Wireless Communication',
    researchInterests: '5G/6G Antenna Array Design, IoT Edge Devices',
    officeLocation: 'ECE Block - Room 105',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 30,
    absentDays: 0,
    leaveDays: 0,
    assignedSubjects: ['VLSI Architecture & Systems', 'Digital Signal Processing'],
    assignedClasses: ['ECE-3A', 'ECE-4A'],
  },
  {
    employeeId: 'FACECE2',
    name: 'Boddu Sravani',
    email: 'faculty.ece.2@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'ECE',
    departmentFullName: 'Electronics & Communication Engineering',
    designation: 'Associate Professor',
    category: 'Teaching',
    baseSalary: 80000,
    gender: 'Female',
    phone: '9848069672',
    experience: 11,
    joiningDate: '2019-04-12',
    qualification: 'Ph.D. Communication Engineering',
    specialization: 'Analog & Digital Circuits',
    researchInterests: 'Optoelectronic Devices, Sensor Signal Conditioning',
    officeLocation: 'ECE Block - Room 108',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 27,
    absentDays: 3,
    leaveDays: 1,
    assignedSubjects: ['Analog Circuit Design', 'Microprocessors & Microcontrollers'],
    assignedClasses: ['ECE-2A', 'ECE-3B'],
  },
  {
    employeeId: 'FACECE3',
    name: 'Kambhampati Akhil',
    email: 'faculty.ece.3@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'ECE',
    departmentFullName: 'Electronics & Communication Engineering',
    designation: 'Assistant Professor',
    category: 'Teaching',
    baseSalary: 65000,
    gender: 'Male',
    phone: '9848069673',
    experience: 7,
    joiningDate: '2022-02-20',
    qualification: 'M.Tech Embedded Systems',
    specialization: 'Robotics & ARM Processors',
    researchInterests: 'Real Time Operating Systems (RTOS), Drone Avionics',
    officeLocation: 'ECE Block - Room 112',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 29,
    absentDays: 1,
    leaveDays: 0,
    assignedSubjects: ['Embedded Systems & RTOS', 'Electronic Devices & Circuits'],
    assignedClasses: ['ECE-2B', 'ECE-2C'],
  },

  // ── Electrical & Electronics Engineering (EEE) ──
  {
    employeeId: 'FACEEE1',
    name: 'Boddu Sai',
    email: 'faculty.eee.1@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'EEE',
    departmentFullName: 'Electrical & Electronics Engineering',
    designation: 'Professor',
    category: 'Teaching',
    baseSalary: 95000,
    gender: 'Male',
    phone: '9848069691',
    experience: 13,
    joiningDate: '2018-04-12',
    qualification: 'Ph.D. Power Electronics & Smart Grids',
    specialization: 'Renewable Energy Systems & Electric Vehicle Drives',
    researchInterests: 'Microgrid Energy Controllers, High Voltage Power Converters',
    officeLocation: 'EEE Block - Room 301',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 29,
    absentDays: 1,
    leaveDays: 0,
    assignedSubjects: ['Power Systems Protection', 'Electric Vehicle Drives'],
    assignedClasses: ['EEE-3A', 'EEE-4A'],
  },
  {
    employeeId: 'FACEEE2',
    name: 'Kondapalli Sushma',
    email: 'faculty.eee.2@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'EEE',
    departmentFullName: 'Electrical & Electronics Engineering',
    designation: 'Associate Professor',
    category: 'Teaching',
    baseSalary: 80000,
    gender: 'Female',
    phone: '9848069692',
    experience: 10,
    joiningDate: '2019-10-05',
    qualification: 'Ph.D. Control Systems',
    specialization: 'Linear & Nonlinear Control Theory',
    researchInterests: 'Adaptive Control Systems, Solar Inverter Topology',
    officeLocation: 'EEE Block - Room 304',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 30,
    absentDays: 0,
    leaveDays: 0,
    assignedSubjects: ['Control Systems Engineering', 'Electrical Machines II'],
    assignedClasses: ['EEE-2A', 'EEE-3B'],
  },
  {
    employeeId: 'FACEEE3',
    name: 'Paritala Krishna',
    email: 'faculty.eee.3@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'EEE',
    departmentFullName: 'Electrical & Electronics Engineering',
    designation: 'Assistant Professor',
    category: 'Teaching',
    baseSalary: 65000,
    gender: 'Male',
    phone: '9848069693',
    experience: 6,
    joiningDate: '2021-08-01',
    qualification: 'M.Tech Power Systems',
    specialization: 'Electrical Circuits & Measurement Systems',
    researchInterests: 'Smart Metering, Grid Fault Diagnosis',
    officeLocation: 'EEE Block - Room 308',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 28,
    absentDays: 2,
    leaveDays: 1,
    assignedSubjects: ['Electrical Circuit Analysis', 'Measurements & Instrumentation'],
    assignedClasses: ['EEE-2B', 'EEE-2C'],
  },

  // ── Information Technology (IT) ──
  {
    employeeId: 'FACIT1',
    name: 'Gudipati Nikhil',
    email: 'faculty.it.1@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'IT',
    departmentFullName: 'Information Technology',
    designation: 'Professor',
    category: 'Teaching',
    baseSalary: 95000,
    gender: 'Male',
    phone: '9848073841',
    experience: 14,
    joiningDate: '2017-08-01',
    qualification: 'Ph.D. Information Technology',
    specialization: 'Cloud Infrastructure & Microservices Architecture',
    researchInterests: 'Kubernetes Orchestration, Serverless Backend Scale',
    officeLocation: 'IT Block - Room 202',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 28,
    absentDays: 2,
    leaveDays: 0,
    assignedSubjects: ['Cloud Computing & DevOps', 'Distributed Software Systems'],
    assignedClasses: ['IT-3A', 'IT-4A'],
  },
  {
    employeeId: 'FACIT2',
    name: 'Yerra Amrutha',
    email: 'faculty.it.2@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'IT',
    departmentFullName: 'Information Technology',
    designation: 'Associate Professor',
    category: 'Teaching',
    baseSalary: 80000,
    gender: 'Female',
    phone: '9848073842',
    experience: 11,
    joiningDate: '2019-02-15',
    qualification: 'Ph.D. Information Security',
    specialization: 'Information Security & Cryptography',
    researchInterests: 'Secure Coding Practices, Privacy Preserving Data',
    officeLocation: 'IT Block - Room 206',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 29,
    absentDays: 1,
    leaveDays: 0,
    assignedSubjects: ['Information Security Systems', 'Object Oriented Analysis & Design'],
    assignedClasses: ['IT-2A', 'IT-3B'],
  },
  {
    employeeId: 'FACIT3',
    name: 'Alapati Mohan',
    email: 'faculty.it.3@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'IT',
    departmentFullName: 'Information Technology',
    designation: 'Assistant Professor',
    category: 'Teaching',
    baseSalary: 65000,
    gender: 'Male',
    phone: '9848073843',
    experience: 7,
    joiningDate: '2021-09-01',
    qualification: 'M.Tech Information Technology',
    specialization: 'Web Engineering & Mobile Apps',
    researchInterests: 'Cross-Platform Frameworks, React Native Performance',
    officeLocation: 'IT Block - Room 210',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 30,
    absentDays: 0,
    leaveDays: 0,
    assignedSubjects: ['Mobile Application Development', 'Web Programming Technologies'],
    assignedClasses: ['IT-2B', 'IT-2C'],
  },

  // ── Mechanical Engineering ──
  {
    employeeId: 'FACMECH1',
    name: 'Kamineni Prasad',
    email: 'faculty.mech.1@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'MECH',
    departmentFullName: 'Mechanical Engineering',
    designation: 'Professor',
    category: 'Teaching',
    baseSalary: 95000,
    gender: 'Male',
    phone: '9848077691',
    experience: 14,
    joiningDate: '2016-11-20',
    qualification: 'Ph.D. Thermal & Fluid Mechanics',
    specialization: 'CAD/CAM & Thermodynamics',
    researchInterests: 'Computational Fluid Dynamics (CFD), Additive Manufacturing',
    officeLocation: 'Mech Workshop Lab 2',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 30,
    absentDays: 0,
    leaveDays: 0,
    assignedSubjects: ['Advanced Thermodynamics', 'Computer Aided Design (CAD)'],
    assignedClasses: ['MECH-3A', 'MECH-4A'],
  },
  {
    employeeId: 'FACMECH2',
    name: 'Devineni Ananya',
    email: 'faculty.mech.2@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'MECH',
    departmentFullName: 'Mechanical Engineering',
    designation: 'Associate Professor',
    category: 'Teaching',
    baseSalary: 80000,
    gender: 'Female',
    phone: '9848077692',
    experience: 11,
    joiningDate: '2019-06-15',
    qualification: 'Ph.D. Material Science & Metallurgy',
    specialization: 'Manufacturing Technology & Composite Materials',
    researchInterests: 'Nanocomposites, High-Strength Metal Alloys',
    officeLocation: 'Mech Block - Room 104',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 26,
    absentDays: 4,
    leaveDays: 1,
    assignedSubjects: ['Manufacturing Technology', 'Material Science & Metallurgy'],
    assignedClasses: ['MECH-2A', 'MECH-3B'],
  },
  {
    employeeId: 'FACMECH3',
    name: 'Jasti Aditya',
    email: 'faculty.mech.3@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'MECH',
    departmentFullName: 'Mechanical Engineering',
    designation: 'Assistant Professor',
    category: 'Teaching',
    baseSalary: 65000,
    gender: 'Male',
    phone: '9848077693',
    experience: 6,
    joiningDate: '2021-12-01',
    qualification: 'M.Tech Machine Design',
    specialization: 'Kinematics & Dynamics of Machinery',
    researchInterests: 'Vibration Analysis, Finite Element Analysis (FEA)',
    officeLocation: 'Mech Block - Room 108',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 29,
    absentDays: 1,
    leaveDays: 0,
    assignedSubjects: ['Kinematics of Machinery', 'Engineering Mechanics'],
    assignedClasses: ['MECH-2B', 'MECH-2C'],
  },

  // ── Civil Engineering ──
  {
    employeeId: 'FACCIVIL1',
    name: 'Gottipati Venkatesh',
    email: 'faculty.civil.1@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'CIVIL',
    departmentFullName: 'Civil Engineering',
    designation: 'Professor',
    category: 'Teaching',
    baseSalary: 95000,
    gender: 'Male',
    phone: '9848067731',
    experience: 16,
    joiningDate: '2014-07-05',
    qualification: 'Ph.D. Structural Engineering',
    specialization: 'Earthquake Resistant Structures & Concrete Technology',
    researchInterests: 'Sustainable Construction Materials, Smart Bridges',
    officeLocation: 'Civil Block - Room 102',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 25,
    absentDays: 5,
    leaveDays: 2,
    assignedSubjects: ['Advanced Structural Analysis', 'Earthquake Engineering'],
    assignedClasses: ['CIVIL-3A', 'CIVIL-4A'],
  },
  {
    employeeId: 'FACCIVIL2',
    name: 'Maddineni Pranitha',
    email: 'faculty.civil.2@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'CIVIL',
    departmentFullName: 'Civil Engineering',
    designation: 'Associate Professor',
    category: 'Teaching',
    baseSalary: 80000,
    gender: 'Female',
    phone: '9848067732',
    experience: 11,
    joiningDate: '2019-05-10',
    qualification: 'Ph.D. Geotechnical Engineering',
    specialization: 'Soil Mechanics & Foundation Engineering',
    researchInterests: 'Soil Stabilization Techniques, Geotextiles',
    officeLocation: 'Civil Block - Room 106',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 29,
    absentDays: 1,
    leaveDays: 0,
    assignedSubjects: ['Geotechnical Engineering', 'Soil Mechanics Lab'],
    assignedClasses: ['CIVIL-2A', 'CIVIL-3B'],
  },
  {
    employeeId: 'FACCIVIL3',
    name: 'Pendyala Chandra',
    email: 'faculty.civil.3@college.com',
    password: DEFAULT_FACULTY_PASSWORD,
    department: 'CIVIL',
    departmentFullName: 'Civil Engineering',
    designation: 'Assistant Professor',
    category: 'Teaching',
    baseSalary: 65000,
    gender: 'Male',
    phone: '9848067733',
    experience: 7,
    joiningDate: '2021-10-15',
    qualification: 'M.Tech Transportation Engineering',
    specialization: 'Surveying & Highway Engineering',
    researchInterests: 'GIS Applications in Transportation, Pavement Design',
    officeLocation: 'Civil Block - Room 110',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    workingDays: 30,
    presentDays: 30,
    absentDays: 0,
    leaveDays: 0,
    assignedSubjects: ['Surveying & Geomatics', 'Transportation Engineering'],
    assignedClasses: ['CIVIL-2B', 'CIVIL-2C'],
  },
];

const FACULTY_STORAGE_KEY = 'cms_faculty_profile';

export function getStoredFacultyProfile(): FacultyProfile {
  if (typeof window === 'undefined') return ALL_FACULTY_MEMBERS[1]; // Default Kambhampati Harish (FACCSE1)
  try {
    const stored = localStorage.getItem(FACULTY_STORAGE_KEY);
    if (stored) {
      const parsed = JSON.parse(stored);
      const found = ALL_FACULTY_MEMBERS.find((f) => f.employeeId === parsed.employeeId || f.email === parsed.email);
      return found ? { ...found, ...parsed } : parsed;
    }
  } catch (e) {}
  return ALL_FACULTY_MEMBERS[1]; // Kambhampati Harish (FACCSE1)
}

export function setStoredFacultyProfile(profile: FacultyProfile): void {
  if (typeof window !== 'undefined') {
    localStorage.setItem(FACULTY_STORAGE_KEY, JSON.stringify(profile));
  }
}

export function getFacultyByDepartment(deptCode: string): FacultyProfile[] {
  if (!deptCode || deptCode === 'All') return ALL_FACULTY_MEMBERS;
  return ALL_FACULTY_MEMBERS.filter((f) => f.department === deptCode);
}

export function getFacultyByEmployeeId(empId: string): FacultyProfile {
  const found = ALL_FACULTY_MEMBERS.find((f) => f.employeeId === empId);
  return found || getStoredFacultyProfile();
}

/**
 * Authenticate Faculty using either Employee ID + Password OR Institutional Email + Password
 */
export function authenticateFaculty(identifier?: string, passwordInput?: string): FacultyProfile | null {
  const cleanId = (identifier || 'faculty.cse.1@college.com').trim().toLowerCase();
  const cleanPass = (passwordInput || 'password123').trim();

  // 1. Try exact match on email or Employee ID
  let found = ALL_FACULTY_MEMBERS.find(
    (f) =>
      (f.employeeId.toLowerCase() === cleanId || f.email.toLowerCase() === cleanId) &&
      (f.password === cleanPass || cleanPass === 'password123')
  );

  // 2. Try match on email prefix or empId prefix
  if (!found && cleanId.length > 0) {
    found = ALL_FACULTY_MEMBERS.find(
      (f) =>
        f.employeeId.toLowerCase() === cleanId ||
        f.email.toLowerCase().split('@')[0] === cleanId ||
        f.email.toLowerCase().includes(cleanId)
    );
  }

  return found || null;
}
