import {
  LayoutDashboard,
  Users,
  GraduationCap,
  BookOpen,
  CalendarCheck,
  Award,
  Clock,
  Heart,
  FlaskConical,
  Database,
  ClipboardList,
  Sparkles,
  Activity,
  MessageSquare,
  FileText,
  Bell,
  Settings,
  ShieldAlert,
} from 'lucide-react';
import { HODNavItem } from '../types';

export const HOD_NAV_ITEMS: HODNavItem[] = [
  { to: '/hod/dashboard', label: 'Dashboard', icon: LayoutDashboard, exact: true, description: 'Department Overview & KPIs' },
  { to: '/hod/students', label: 'Student Management', icon: Users, description: 'Department Enrolled Students' },
  { to: '/hod/faculty', label: 'Faculty Management', icon: GraduationCap, description: 'Professors & Workloads' },
  { to: '/hod/academics', label: 'Academic Management', icon: BookOpen, description: 'Curriculum & Syllabi' },
  { to: '/hod/attendance', label: 'Attendance', icon: CalendarCheck, description: 'Class Attendance Audits' },
  { to: '/hod/examinations', label: 'Examinations', icon: Award, description: 'Internal & End Sem Exams' },
  { to: '/hod/timetable', label: 'Timetable', icon: Clock, description: 'Class & Lab Schedules' },
  { to: '/hod/mentoring', label: 'Mentoring', icon: Heart, description: 'Student Advisory Logs' },
  { to: '/hod/research', label: 'Research', icon: FlaskConical, description: 'Publications & Grants' },
  { to: '/hod/resources', label: 'Resources', icon: Database, description: 'Labs & Equipment Assets' },
  { to: '/hod/approvals', label: 'Approvals', icon: ClipboardList, description: 'Leave & Signoff Workflow' },
  { to: '/hod/events', label: 'Events', icon: Sparkles, description: 'Dept Seminars & Symposia' },
  { to: '/hod/reports', label: 'Reports', icon: Activity, description: 'Academic Analytics' },
  { to: '/hod/communication', label: 'Communication', icon: MessageSquare, description: 'Broadcasts & Notices' },
  { to: '/hod/documents', label: 'Documents', icon: FileText, description: 'BOS & Syllabus Records' },
  { to: '/hod/notifications', label: 'Notifications', icon: Bell, description: 'Alert Center' },
  { to: '/hod/settings', label: 'Settings', icon: Settings, description: 'Department Configuration' },
  { to: '/hod/audit-logs', label: 'Audit Logs', icon: ShieldAlert, description: 'System Change Tracking' },
];
